[workspace]

members = [ "tpchgen", "tpcdsgen" , "tpchgen-arrow", "tpchgen-cli", "tpcdsgen-arrow", "tpcgen-cli", "tpchgen-sorted"]

resolver = "2"

[workspace.package]
authors = ["clflushopt", "alamb"]
edition = "2021"
homepage = "https://github.com/datafusion-contrib/tpcgen-rs"
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/datafusion-contrib/tpcgen-rs"
version = "3.0.0"

[workspace.dependencies]
arrow = { version = "59", default-features = false, features = ["prettyprint"] }
arrow-csv = "59"

[profile.release]
codegen-units = 1
lto = true
strip = "debuginfo"
